# Generated by Django 4.2.7 on 2023-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ID_Paciente', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Data_Nascimento', models.DateField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('peso', models.CharField(max_length=3)),
            ],
        ),
    ]
