# Generated by Django 4.2.7 on 2023-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Data_Nascimento',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='ID_Paciente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
